
WITH MEMBER_MONTH AS (
SELECT DISTINCT MM.POPULATION_ID,
                MM.ENROLLMENT_SOURCE_DESCRIPTION,
                MM.CLAIM_SOURCE_DESCRIPTION,
                MM.BENEFIT_TYPE,
                MM.MONTH_DATE_ID,
                MM.EMPI_ID
FROM <ANALYST_SCHEMA>.DI_PR_MEMBER_MONTHS MM
WHERE MM.POPULATION_ID = '<POPULATION_ID>'
  AND MM.PLAN_NAME IS NOT NULL
  AND MM.PLAN_NAME NOT IN (<PLAN_NAME_EXCLUSION_LIST>)
  AND MM.CLAIM_SOURCE_DESCRIPTION IN (<SOURCE_LIST>)
  AND MM.MONTH >= '<BEG_DATE>'
  AND MM.MONTH <= '<END_DATE>'
  AND MM.CMS_EXCLUSION_IND <> 1
),

SERVICE_METRICS AS (
SELECT CD.POPULATION_ID,
       CD.CLAIM_ID,
       CD.EMPI_ID,
       CD.SOURCE_DESCRIPTION,
       COUNT(DISTINCT CD.LINE_NUMBER) AS SERVICE_LINE_COUNT,
          SUM(CD.PAID_AMOUNT::FLOAT) AS SERVICE_PAID_AMOUNT,
          SUM(CD.BILLED_AMOUNT::FLOAT) AS SERVICE_BILLED_AMOUNT,
          SUM(CD.SERVICE_ALLOWED_AMOUNT::FLOAT) AS SERVICE_ALLOWED_AMOUNT
FROM <SCHEMA>.PH_F_CLAIM_DETAIL CD
WHERE CD.POPULATION_ID = '<POPULATION_ID>'
  AND (CD.SERVICE_STATUS <> 'D'
       OR CD.SERVICE_STATUS IS NULL)
  AND CD.SOURCE_DESCRIPTION IN (<SOURCE_LIST>)
GROUP BY 1,
         2,
         3,
         4
),

CLAIM_DATA AS (
SELECT C.POPULATION_ID,
       C.SOURCE_DESCRIPTION,
       C.INCURRED_FROM_MONTH_ID,
       C.EMPI_ID,
       C.FORM_TYPE,
       C.CLAIM_ID,
       C.TOTAL_PAID_CHARGE,
       C.TOTAL_BILLED_CHARGE,
       C.ADJUDICATED_PAYER_ALLOWED_AMOUNT
FROM <SCHEMA>.PH_F_CLAIM C
WHERE C.POPULATION_ID = '<POPULATION_ID>'
  AND C.FORM_TYPE IN ('I',
                      'P',
                      'Rx')
  AND (C.CLAIM_STATUS IN (<CLAIM_STATUS_LIST>)
       OR C.CLAIM_STATUS IS NULL)
  AND C.INCURRED_FROM_MONTH >= '<BEGIN_DATE>'
  AND C.INCURRED_FROM_MONTH <= '<END_DATE>'
  AND C.PAID_DATE <= '<PAID_DATE>'
  AND NOT EXISTS
    (SELECT A.EMPI_ID
     FROM PH_F_CMS_MEMBER_INFO A
     WHERE A.CMS_MEMBER_INFO_TYPE ='CMS_ACO_EXCLUSION_REASON'
       AND A.EFFECTIVE_PERIOD_START_DT_ID = C.INCURRED_FROM_MONTH_ID
       AND A.EMPI_ID = C.EMPI_ID )
)

SELECT NOW() AS SNAPSHOT_DT_TM,
       '<SCHEMA>' AS CLIENT_SCHEMA,
       C.POPULATION_ID,
       C.SOURCE_DESCRIPTION,
       C.INCURRED_FROM_MONTH_ID AS MONTH_DATE_ID,
       CASE
           WHEN MM.EMPI_ID IS NULL THEN 0
           ELSE 1
       END AS MEMBER_ENROLLED_IND,
       COUNT(DISTINCT CASE
                          WHEN C.FORM_TYPE IN ('I', 'P') THEN C.CLAIM_ID
                      END) AS TOTAL_MED_CLAIM_COUNT,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN SM.SERVICE_LINE_COUNT
               ELSE 0
           END) AS TOTAL_MED_CLAIM_LINE_COUNT,
       COUNT(DISTINCT CASE
                          WHEN C.FORM_TYPE IN ('Rx') THEN C.CLAIM_ID
                      END) AS TOTAL_RX_CLAIM_COUNT,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN SM.SERVICE_LINE_COUNT
               ELSE 0
           END) AS TOTAL_RX_CLAIM_LINE_COUNT,
       SUM(C.TOTAL_PAID_CHARGE) AS HDR_TTL_PAID,
       SUM(C.TOTAL_BILLED_CHARGE) AS HDR_TTL_BILLED,
       SUM(C.ADJUDICATED_PAYER_ALLOWED_AMOUNT) AS HDR_TTL_ALLOWED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN C.TOTAL_PAID_CHARGE
           END) AS HDR_TTL_PAID_MED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN C.TOTAL_PAID_CHARGE
           END) AS HDR_TTL_PAID_RX,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN C.TOTAL_BILLED_CHARGE
           END) AS HDR_TTL_BILLED_MED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN C.TOTAL_BILLED_CHARGE
           END) AS HDR_TTL_BILLED_RX,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN C.ADJUDICATED_PAYER_ALLOWED_AMOUNT
           END) AS HDR_TTL_ALLOWED_MED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN C.ADJUDICATED_PAYER_ALLOWED_AMOUNT
           END) AS HDR_TTL_ALLOWED_RX,
       SUM(SM.SERVICE_LINE_COUNT) AS SERVICE_LINE_COUNT,
       SUM(SM.SERVICE_PAID_AMOUNT) AS SERVICE_PAID_AMOUNT,
       SUM(SM.SERVICE_BILLED_AMOUNT) AS SERVICE_BILLED_AMOUNT,
       SUM(SM.SERVICE_ALLOWED_AMOUNT) AS SERVICE_ALLOWED_AMOUNT,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN SM.SERVICE_PAID_AMOUNT
           END) AS SVC_TTL_PAID_MED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN SM.SERVICE_PAID_AMOUNT
           END) AS SVC_TTL_PAID_RX,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN SM.SERVICE_BILLED_AMOUNT
           END) AS SVC_TTL_BILLED_MED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN SM.SERVICE_BILLED_AMOUNT
           END) AS SVC_TTL_BILLED_RX,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('I', 'P') THEN SM.SERVICE_ALLOWED_AMOUNT
           END) AS SVC_TTL_ALLOWED_MED,
       SUM(CASE
               WHEN C.FORM_TYPE IN ('Rx') THEN SM.SERVICE_ALLOWED_AMOUNT
           END) AS SVC_TTL_ALLOWED_RX
FROM <SCHEMA>.PH_F_CLAIM C
LEFT JOIN MEMBER_MONTH MM ON (MM.EMPI_ID = C.EMPI_ID
                              AND MM.POPULATION_ID = C.POPULATION_ID
                              AND MM.CLAIM_SOURCE_DESCRIPTION = C.SOURCE_DESCRIPTION
                              AND MM.MONTH_DATE_ID = C.INCURRED_FROM_MONTH_ID
                              AND CASE
                                      WHEN C.FORM_TYPE IN ('I',
                                                           'P') THEN MM.BENEFIT_TYPE ILIKE '%MEDICAL%'
                                      WHEN C.FORM_TYPE = 'Rx' THEN MM.BENEFIT_TYPE ILIKE '%PHARM%'
                                  END)
LEFT JOIN SERVICE_METRICS SM ON (C.EMPI_ID = SM.EMPI_ID
                                 AND C.CLAIM_ID = SM.CLAIM_ID
                                 AND C.POPULATION_ID = SM.POPULATION_ID
                                 AND C.SOURCE_DESCRIPTION = SM.SOURCE_DESCRIPTION)
WHERE (C.CLAIM_STATUS <> 'D' OR C.CLAIM_STATUS IS NULL)
GROUP BY 3,
         4,
         5,
         6
